name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    
    # WAJIB: Izin Write agar bisa membuat Release
    permissions:
      contents: write

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git ccache automake flex lzop bison \
        gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils \
        bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush \
        schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev \
        pwgen libswitch-perl policycoreutils minicom libxml-simple-perl \
        libxml-sax-base-perl libxml-sax-expat-perl bc libncurses5-dev \
        lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-dev \
        libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 \
        lzop pngcrush schedtool squashfs-tools imagemagick xsltproc zip \
        zlib1g-dev python3 python3-pip wget coreutils

    - name: Setup KernelSU (MamboSU)
      run: |
        echo "Applying KernelSU Patch..."
        curl -LSs "https://raw.githubusercontent.com/RapliVx/KernelSU/refs/heads/master/kernel/setup.sh" | bash -s xxksu
        echo "KernelSU Setup Complete."

    - name: Run Build Script
      env:
        # Masukkan Secrets agar script compile.sh bisa kirim notif Start/Fail
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        NAME_KERNEL: "FranxxCORE"
      run: |
        chmod +x compile.sh
        ./compile.sh

    # --- BAGIAN RELEASE GITHUB ---

    - name: Generate Release Tag
      id: tag
      run: |
        # Membuat tag unik berdasarkan Tanggal-Jam
        echo "release_tag=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
        echo "Tag generated: $(date +'%Y.%m.%d-%H%M')"

    - name: Create Release and Upload
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: "FranxxCORE Build - ${{ steps.tag.outputs.release_tag }}"
        # Mengambil file dari folder final_zips yang dibuat oleh script compile.sh
        files: final_zips/*.zip
        draft: false
        prerelease: false
        body: |
          ### 🚀 Automated Kernel Build
          **Date:** ${{ steps.tag.outputs.release_tag }}
          **Kernel Name:** FranxxCORE
          
          *Build completed successfully via GitHub Actions.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
